# Data Integration

### In this File, we are gonna integrate all the three datasets of Starbucks so that we have a better picture for customer analysis, segmentation and recommendation

## -----------------------------------------------------------------------------

## 1. Import Libraries

In [200]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("Libraries are loaded successfully")

Libraries are loaded successfully

## ------------------------------------------------------------------------------

## 2. Loading Cleaned datasets

In [201]:
profile = pd.read_csv("../cleaned_data/profile_cleaned.csv")
portfolio = pd.read_csv("../cleaned_data/portfolio_cleaned.csv")
transcript = pd.read_csv("../cleaned_data/transcript_cleaned.csv")

print("Datasets are loaded successfully")

Datasets are loaded successfully

## ----------------------------------------------------------------------------------

## 3. Checking the dimensions of the Datasets

In [202]:
print("Dimensions of print dataset :- ", profile.shape)
print("Dimensions of portfolio dataset :- ", portfolio.shape)
print("Dimensions of transcript dataset :- ", transcript.shape)

Dimensions of print dataset :-  (17000, 5)
Dimensions of portfolio dataset :-  (10, 6)
Dimensions of transcript dataset :-  (306534, 4)

## -----------------------------------------------------------------------------

## 4. Previewing the Datasets

In [203]:
portfolio.head()
print("")
profile.head()
print("")
transcript.head()

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

## ------------------------------------------------------------------------------------

## 5. Understanding the common keys

In [204]:
print("Columns of the Profile dataset")
print(profile.columns)

print("Columns of the Profile dataset")
print(portfolio.columns)

print("Columns of the Profile dataset")
print(transcript.columns)

Columns of the Profile dataset
Index(['gender', 'age', 'id', 'became_member_on', 'income'], dtype='str')
Columns of the Profile dataset
Index(['reward', 'channels', 'difficulty', 'duration', 'offer_type', 'id'], dtype='str')
Columns of the Profile dataset
Index(['person', 'event', 'value', 'time'], dtype='str')

## --------------------------------------------------------------------------------------

## 6. Extracting Offer IDs from Transcript Dataset

In [205]:
transcript["value"].head(20)

0     {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'}
1     {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
2     {'offer id': '2906b810c7d4411798c6938adc9daaa5'}
3     {'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}
4     {'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'}
5     {'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'}
6     {'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'}
7     {'offer id': '3f207df678b143eea3cee63160fa8bed'}
8     {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
9     {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
10    {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
11    {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
12    {'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}
13    {'offer id': '3f207df678b143eea3cee63160fa8bed'}
14    {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
15    {'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}
16    {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}
17    {'offer id': '2906b810c7d4411798c6938adc9daaa5'}
18    {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'}
19    {'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}
Name: value, dtype: str

## --------------------------------------------------------------------------------------

## 7. Checking Event Types

In [206]:
transcript["event"].value_counts()

event
transaction        138953
offer received      76277
offer viewed        57725
offer completed     33579
Name: count, dtype: int64

## --------------------------------------------------------------------------------------

## 8. Extracting Offer IDs from Value Column

In [207]:
import ast 
def extract_offer_id(value):
    value_dict = ast.literal_eval(value)

    if"offer id" in value_dict:
        return value_dict["offer id"]
    elif "offer_id" in value_dict:
        return value_dict ["offer_id"]
    else:
        return None
    
transcript["offer_id"] = transcript["value"].apply(extract_offer_id)
transcript.head()

,person,event,value,time,offer_id
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,9b98b8c7a33c4b65b9aebfe6a799e6d9
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0b1e1539f2cc45b7b9fa7c272da2e1d7
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,2906b810c7d4411798c6938adc9daaa5
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,fafdcd668e3743c1bb461111dcafc2a4
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,4d5c57ea9a6940dd891ad53e9dbe8da0

## ----------------------------------------------------------------------------------------

## 9. Verifying extracted offer IDs

In [208]:
transcript[["offer_id"]].head(10)

                           offer_id
0  9b98b8c7a33c4b65b9aebfe6a799e6d9
1  0b1e1539f2cc45b7b9fa7c272da2e1d7
2  2906b810c7d4411798c6938adc9daaa5
3  fafdcd668e3743c1bb461111dcafc2a4
4  4d5c57ea9a6940dd891ad53e9dbe8da0
5  f19421c1d4aa40978ebb69ca19b0e20d
6  2298d6c36e964ae4a3e7e9706d1fb8c2
7  3f207df678b143eea3cee63160fa8bed
8  0b1e1539f2cc45b7b9fa7c272da2e1d7
9  0b1e1539f2cc45b7b9fa7c272da2e1d7

##-------------------------------------------------------------------------------------

## 10. Checking Missing offer IDs

In [209]:
print("Total missing offer ids :- ", transcript["offer_id"].isnull().sum())

Total missing offer ids :-  138953

## -------------------------------------------------------------------------------------

## 11. Integrating Transcript and Portfolio

In [210]:
transcript_portfolio = pd.merge(
    transcript,
    portfolio,
    left_on = "offer_id",
    right_on = "id",
    how = "left"
)

print("Shape of the Dataset after merging both transcript and portfolio :- ", transcript_portfolio.shape)

Shape of the Dataset after merging both transcript and portfolio :-  (306534, 11)

In [211]:
transcript_portfolio.head()

,person,event,value,time,offer_id,reward,channels,difficulty,duration,offer_type,id
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0,"['web', 'email']",20.0,10.0,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,2906b810c7d4411798c6938adc9daaa5,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,2906b810c7d4411798c6938adc9daaa5
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,fafdcd668e3743c1bb461111dcafc2a4,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,fafdcd668e3743c1bb461111dcafc2a4
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0

## ---------------------------------------------------------------------------------------

## 12. Integrating all the data to make master dataset

In [212]:
master_data = pd.merge(
    transcript_portfolio,
    profile,
    left_on = "person",
    right_on = "id",
    how = "left"
)

print("Final Master Dataset Shape :- ", master_data.shape)

Final Master Dataset Shape :-  (306534, 16)

In [213]:
master_data.head()

,person,event,value,time,offer_id,reward,channels,difficulty,duration,offer_type,id_x,gender,age,id_y,became_member_on,income
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,"['web', 'email', 'mobile']",5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9,F,75.0,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0,"['web', 'email']",20.0,10.0,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7,Unknown,55.0,a03223e636434f42ac4c3df47e8bac43,20170804,64000.0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,2906b810c7d4411798c6938adc9daaa5,2.0,"['web', 'email', 'mobile']",10.0,7.0,discount,2906b810c7d4411798c6938adc9daaa5,M,68.0,e2127556f4f64592b11af22de27a7932,20180426,70000.0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,fafdcd668e3743c1bb461111dcafc2a4,2.0,"['web', 'email', 'mobile', 'social']",10.0,10.0,discount,fafdcd668e3743c1bb461111dcafc2a4,Unknown,55.0,8ec6ce2a7e7949b1bf142def7d0e0586,20170925,64000.0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,"['web', 'email', 'mobile', 'social']",10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0,Unknown,55.0,68617ca6246f4fbc85e91a2a49552598,20171002,64000.0

## --------------------------------------------------------------------------------

## 13. Verifying Master Dataset

In [214]:
print(master_data.shape)
print("")
print(master_data.columns)
print("")
print(master_data[[
    "person",
    "event",
    "offer_id",
    "reward",
    "gender",
    "age",
    "income"
]].head())

(306534, 16)

Index(['person', 'event', 'value', 'time', 'offer_id', 'reward', 'channels',
       'difficulty', 'duration', 'offer_type', 'id_x', 'gender', 'age', 'id_y',
       'became_member_on', 'income'],
      dtype='str')

                             person           event  \
0  78afa995795e4d85b5d9ceeca43f5fef  offer received
1  a03223e636434f42ac4c3df47e8bac43  offer received
2  e2127556f4f64592b11af22de27a7932  offer received
3  8ec6ce2a7e7949b1bf142def7d0e0586  offer received
4  68617ca6246f4fbc85e91a2a49552598  offer received

                           offer_id  reward   gender   age    income
0  9b98b8c7a33c4b65b9aebfe6a799e6d9     5.0        F  75.0  100000.0
1  0b1e1539f2cc45b7b9fa7c272da2e1d7     5.0  Unknown  55.0   64000.0
2  2906b810c7d4411798c6938adc9daaa5     2.0        M  68.0   70000.0
3  fafdcd668e3743c1bb461111dcafc2a4     2.0  Unknown  55.0   64000.0
4  4d5c57ea9a6940dd891ad53e9dbe8da0    10.0  Unknown  55.0   64000.0

## ---------------------------------------------------------------------------------------

## 14. Saving Master Data File

In [215]:
master_data.to_csv("../cleaned_data/master_data.csv", index = False)

print("Master dataset saved successfully")

Master dataset saved successfully