# Data Preprocessing

### In this notebook, we are gonna focus on cleaning and preparing the datasets of starbucks before integrating and analysing them

## ---------------------------------------------------------------------------------

## 1. Import Libraries

In [464]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("The libraries are loaded successfully")

The libraries are loaded successfully

## -----------------------------------------------------------------------------------

## 2. Load Datasets

In [465]:
profile = pd.read_csv("../data/profile.csv")
portfolio = pd.read_csv("../data/portfolio.csv")
transcript = pd.read_csv("../data/transcript.csv")

print("The datasets are loaded succusessfully")

The datasets are loaded succusessfully

## --------------------------------------------------------------------------------

## 3. Inspecting columnns of the Dataset

In [466]:
profile.columns

Index(['Unnamed: 0', 'gender', 'age', 'id', 'became_member_on', 'income'], dtype='str')

In [467]:
portfolio.columns

Index(['Unnamed: 0', 'reward', 'channels', 'difficulty', 'duration',
       'offer_type', 'id'],
      dtype='str')

In [468]:
transcript.columns

Index(['Unnamed: 0', 'person', 'event', 'value', 'time'], dtype='str')

## --------------------------------------------------------------------------------------

## 4. Removing unwanted columns

In [469]:
profile = profile.drop(columns = ["Unnamed: 0"])
portfolio = portfolio.drop(columns = ["Unnamed: 0"])
transcript = transcript.drop(columns = ["Unnamed: 0"])

print("The column named 'Unnamed :0' has been removed successfully")

The column named 'Unnamed :0' has been removed successfully

## ----------------------------------------------------------------------------------

## 5. Verifying Column Removal

In [470]:
print(profile.columns)
print("")
print(portfolio.columns)
print("")
print(transcript.columns)

Index(['gender', 'age', 'id', 'became_member_on', 'income'], dtype='str')

Index(['reward', 'channels', 'difficulty', 'duration', 'offer_type', 'id'], dtype='str')

Index(['person', 'event', 'value', 'time'], dtype='str')

## ----------------------------------------------------------------------------------------

## 6. Inspecting Missing Values

In [471]:
profile[profile["gender"].isnull()].head()

  gender  age                                id  became_member_on  income
0    NaN  118  68be06ca386d4c31939f3a4f0e3dd783          20170212     NaN
2    NaN  118  38fe809add3b4fcf9315a9694bb96ff5          20180712     NaN
4    NaN  118  a03223e636434f42ac4c3df47e8bac43          20170804     NaN
6    NaN  118  8ec6ce2a7e7949b1bf142def7d0e0586          20170925     NaN
7    NaN  118  68617ca6246f4fbc85e91a2a49552598          20171002     NaN

In [472]:
profile[profile["income"].isnull()].head()

  gender  age                                id  became_member_on  income
0    NaN  118  68be06ca386d4c31939f3a4f0e3dd783          20170212     NaN
2    NaN  118  38fe809add3b4fcf9315a9694bb96ff5          20180712     NaN
4    NaN  118  a03223e636434f42ac4c3df47e8bac43          20170804     NaN
6    NaN  118  8ec6ce2a7e7949b1bf142def7d0e0586          20170925     NaN
7    NaN  118  68617ca6246f4fbc85e91a2a49552598          20171002     NaN

In [473]:
print("Total number of rows which has missing data for column named 'gender' :- ", profile["gender"].isnull().sum())
print("Total number of rows which has missing data for column named 'income' :- ", profile["income"].isnull().sum())

Total number of rows which has missing data for column named 'gender' :-  2175
Total number of rows which has missing data for column named 'income' :-  2175

## ----------------------------------------------------------------------------------

## 7. Comparing Missing gender and income records

In [474]:
missing_gender = profile[profile["gender"].isnull()]
missing_income = profile[profile["income"].isnull()]

print("Missing Gender shape :- ", missing_gender.shape)
print("Missing income shape :- ", missing_income.shape)

Missing Gender shape :-  (2175, 5)
Missing income shape :-  (2175, 5)

In [475]:
missing_gender[["id"]].head()
missing_income[["id"]].head()

                                 id
0  68be06ca386d4c31939f3a4f0e3dd783
2  38fe809add3b4fcf9315a9694bb96ff5
4  a03223e636434f42ac4c3df47e8bac43
6  8ec6ce2a7e7949b1bf142def7d0e0586
7  68617ca6246f4fbc85e91a2a49552598

In [476]:
missing_gender_ids = set(missing_gender["id"])
missing_income_ids = set(missing_income["id"])

print(missing_gender_ids == missing_income_ids)

True

## ---------------------------------------------------------------------------------

## 8. Handling Missing gender values

In [477]:
profile["gender"] = profile["gender"].fillna("Unknown")

print("Missing Gender Values After Cleaning :- ")
print(profile["gender"].isnull().sum())

Missing Gender Values After Cleaning :-
0

## ---------------------------------------------------------------------------------

## 9. Gender Distribution after cleaning

In [478]:
profile["gender"].value_counts()

gender
M          8484
F          6129
Unknown    2175
O           212
Name: count, dtype: int64

## ----------------------------------------------------------------------------------

## 10. Investigating income distribution

In [479]:
profile["income"].describe()

count     14825.000000
mean      65404.991568
std       21598.299410
min       30000.000000
25%       49000.000000
50%       64000.000000
75%       80000.000000
max      120000.000000
Name: income, dtype: float64

## ------------------------------------------------------------------------------------

## 11. Handling Missing income values

In [480]:
median_income = profile["income"].median()
print("The median of the income is :- ", median_income)

The median of the income is :-  64000.0

In [481]:
profile["income"] = profile["income"].fillna(median_income)

print("Missing income values after cleaning :- ")
print(profile["income"].isnull().sum())

Missing income values after cleaning :-
0

## ---------------------------------------------------------------------------------------

## 12. Verifying Missing values after cleaning

In [482]:
print(profile.isnull().sum())

gender              0
age                 0
id                  0
became_member_on    0
income              0
dtype: int64

## ---------------------------------------------------------------------------------

## 13. Investigating Age Outliers

In [483]:
profile["age"].describe()

count    17000.000000
mean        62.531412
std         26.738580
min         18.000000
25%         45.000000
50%         58.000000
75%         73.000000
max        118.000000
Name: age, dtype: float64

In [484]:
profile[profile["age"] == 118].head()

    gender  age                                id  became_member_on   income
0  Unknown  118  68be06ca386d4c31939f3a4f0e3dd783          20170212  64000.0
2  Unknown  118  38fe809add3b4fcf9315a9694bb96ff5          20180712  64000.0
4  Unknown  118  a03223e636434f42ac4c3df47e8bac43          20170804  64000.0
6  Unknown  118  8ec6ce2a7e7949b1bf142def7d0e0586          20170925  64000.0
7  Unknown  118  68617ca6246f4fbc85e91a2a49552598          20171002  64000.0

In [485]:
profile[profile["age"] == 118].shape

(2175, 5)

In [486]:
profile[profile["age"] == 118][["gender", "age", "income"]].head(10)

     gender  age   income
0   Unknown  118  64000.0
2   Unknown  118  64000.0
4   Unknown  118  64000.0
6   Unknown  118  64000.0
7   Unknown  118  64000.0
9   Unknown  118  64000.0
10  Unknown  118  64000.0
11  Unknown  118  64000.0
17  Unknown  118  64000.0
23  Unknown  118  64000.0

## ------------------------------------------------------------------------------------

## 14. Handling Age Outliers

In [487]:
profile["age"] = profile["age"].replace(118, np.nan)

print("Missing Values for age :- ")
print(profile["age"].isnull().sum())

Missing Values for age :-
2175

In [488]:
profile["age"].describe()

count    14825.000000
mean        54.393524
std         17.383705
min         18.000000
25%         42.000000
50%         55.000000
75%         66.000000
max        101.000000
Name: age, dtype: float64

In [489]:
median_age = profile["age"].median()

print("Median age :- ", median_age)

Median age :-  55.0

## --------------------------------------------------------------------------------------

## 15. Replacing Missing Age values

In [490]:
profile["age"] = profile["age"].fillna(median_age)

print("Missing age values after cleaning the data :- ")
print(profile["age"].isnull().sum())

Missing age values after cleaning the data :-
0

## -----------------------------------------------------------------------------------

## 16. Final Dataset Verification

In [491]:
print(profile.isnull().sum())

gender              0
age                 0
id                  0
became_member_on    0
income              0
dtype: int64

## ---------------------------------------------------------------------------------------

## 17. Saving Cleaned Files

In [492]:
profile.to_csv("../cleaned_data/profile_cleaned.csv", index = False)
print("Profile Cleaned Version saved successfully")

portfolio.to_csv("../cleaned_data/portfolio_cleaned.csv", index = False)
print("Portfolio Cleaned Version saved successfully")

transcript.to_csv("../cleaned_data/transcript_cleaned.csv", index = False)
print("Transcript Cleaned Version saved successfully")

Profile Cleaned Version saved successfully
Portfolio Cleaned Version saved successfully
Transcript Cleaned Version saved successfully